#!/usr/bin/env bash
#
# install.sh — Auto-start the DeepSeek Harness web UI (dsh web) on Linux
# via a systemd unit (requires systemd; dsh must already be installable).
#
# Usage:  ./install.sh [install|start|stop|restart|status|uninstall]
#         (default: install)
#
# Env overrides:
#   DSH_PORT   listen port              (default 3080)
#   DSH_HOST   bind host                (default 127.0.0.1)
#   DSH_USER   systemd service user     (default: current user)
#   DSH_NODE   node binary              (default: first `node` on PATH)
#   DSH_BINJS  dsh entry (bin.js)       (default: auto-detect via npm root -g)
#   DSH_HOME_DIR  service user HOME     (default: from passwd)
#
set -euo pipefail

NAME="dsh-web"
SERVICE="${NAME}.service"
UNIT_DIR="/etc/systemd/system"
UNIT_FILE="${UNIT_DIR}/${SERVICE}"
LIB_DIR="/usr/local/libexec/${NAME}"

PORT="${DSH_PORT:-3080}"
HOST="${DSH_HOST:-127.0.0.1}"
RUN_USER="${DSH_USER:-$(id -un)}"
NODE_BIN="${DSH_NODE:-$(command -v node || true)}"
BIN_JS="${DSH_BINJS:-}"

# re-exec with sudo if not root
if [[ "${EUID}" -ne 0 ]]; then
    if command -v sudo >/dev/null 2>&1; then
        exec sudo "$0" "$@"
    fi
    echo "error: need root (rerun with sudo or as root)" >&2
    exit 1
fi

# ---- helpers ---------------------------------------------------------------
log()  { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }
die()  { log "ERROR: $*"; exit 1; }

resolve_home() { getent passwd "$1" | cut -d: -f6 || true; }

require_systemd() {
    command -v systemctl >/dev/null 2>&1 || die "systemctl not found — this machine does not use systemd"
}

resolve_paths() {
    [[ -n "$NODE_BIN" && -x "$NODE_BIN" ]] || die "node binary not found (set DSH_NODE)"
    if [[ -z "$BIN_JS" ]]; then
        local groot
        groot="$(npm root -g 2>/dev/null || true)"
        if [[ -n "$groot" && -f "${groot}/@deepseek-ai/dsh/lib/bin.js" ]]; then
            BIN_JS="${groot}/@deepseek-ai/dsh/lib/bin.js"
        else
            # last resort: let npx resolve (may hit the network at boot)
            BIN_JS=""
        fi
    fi
    if [[ -n "$BIN_JS" ]]; then
        [[ -f "$BIN_JS" ]] || die "dsh bin.js not found: $BIN_JS (set DSH_BINJS or run: npm i -g @deepseek-ai/dsh)"
    fi
    log "node : $NODE_BIN"
    log "dsh  : ${BIN_JS:-npx @deepseek-ai/dsh (network fallback)}"
    log "bind : ${HOST}:${PORT}  user=$RUN_USER"
}

# wrapper: leaves an existing listener alone (same semantics as the Windows task)
write_wrapper() {
    mkdir -p "$LIB_DIR"
    cat > "${LIB_DIR}/dsh-web-run.sh" <<EOF
#!/usr/bin/env bash
# generated by install.sh; do not edit
PORT="$PORT"
if command -v ss >/dev/null 2>&1; then
    if ss -ltn | awk '{print \$4}' | grep -q ":\${PORT}\$"; then
        echo "port \${PORT} already in use; leaving existing instance alone"
        exit 0
    fi
fi
exec "$NODE_BIN" ${BIN_JS:+$BIN_JS }web --host "$HOST" --port "$PORT"
EOF
    chmod 755 "${LIB_DIR}/dsh-web-run.sh"
    log "wrapper: ${LIB_DIR}/dsh-web-run.sh"
}

write_unit() {
    local home_dir="${DSH_HOME_DIR:-$(resolve_home "$RUN_USER")}"
    [[ -n "$home_dir" ]] || die "cannot resolve home for user '$RUN_USER' (set DSH_HOME_DIR)"
    cat > "$UNIT_FILE" <<EOF
[Unit]
Description=DeepSeek Harness web UI (dsh web)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
Environment=HOME=$home_dir
Environment=DSH_HOME=$home_dir/.dsh
ExecStart=${LIB_DIR}/dsh-web-run.sh
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    log "unit: $UNIT_FILE"
}

cmd_install() {
    require_systemd
    resolve_paths
    write_wrapper
    write_unit
    systemctl daemon-reload
    systemctl enable --now "$SERVICE"
    log "installed + enabled: systemctl status $SERVICE"
}

cmd_uninstall() {
    require_systemd
    systemctl disable --now "$SERVICE" 2>/dev/null || true
    rm -f "$UNIT_FILE"
    rm -rf "$LIB_DIR"
    systemctl daemon-reload
    log "uninstalled"
}

case "${1:-install}" in
    install)   cmd_install ;;
    start)     require_systemd; systemctl start "$SERVICE" ;;
    stop)      require_systemd; systemctl stop "$SERVICE" ;;
    restart)   require_systemd; systemctl restart "$SERVICE" ;;
    status)    require_systemd; systemctl status "$SERVICE" --no-pager || true ;;
    uninstall) cmd_uninstall ;;
    *) echo "usage: $0 [install|start|stop|restart|status|uninstall]" >&2; exit 2 ;;
esac
